In [6]:
import numpy as np

values_u = np.asarray([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
values_v = values_u * 10

y_test = np.full((len(values_u), 2), 0)

y_test[:,0] = values_u
y_test[:,1] = values_v

In [7]:
y_test[:,1]

array([ 10,  20,  30,  40,  50,  60,  70,  80,  90, 100])

In [10]:
y_pred = y_test[:-1,:]
y_true = y_test[1:,:]

In [13]:
print(y_pred[:,0])
print(y_true[:,0])

[1 2 3 4 5 6 7 8 9]
[ 2  3  4  5  6  7  8  9 10]
